# Generated by Django 4.0.3 on 2023-07-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilevo',
            options={'ordering': ('vin',)},
        ),
    ]
