# Generated by Django 4.0.3 on 2023-07-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_automobilevo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilevo',
            options={},
        ),
    ]
