# Generated by Django 4.0.3 on 2023-07-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], default='Created', max_length=20),
        ),
    ]
